### ISSUE TITLE
Dev board confussion

### ISSUE THREAD

**Issue by BannanaWithZipper** [0xbitx/DEDSEC_BLUEJACKER#2]
Hello, I am a bit confused about the dev board mentioned. Can you please help me out with a few clarifications?
1. I already own a ESP32-WROOM-32U, is this ok?
2. In case what I already have is not good. Can you please give me a AliExpress link to the right board, just to make shure?
When I try to look for the specified dev board I get a lot of results and I don`t know which one is the right one. 
Thank you.

**Comment by 0xbitx** [comment]
https://www.aliexpress.com/item/1005006127452526.html

**Comment by BannanaWithZipper** [comment]
Thank you very much!
