### ISSUE TITLE
Long range adapter

### ISSUE THREAD

**Issue by hisbalah** [0xbitx/DEDSEC_BLUEJACKER#3]
Hi Man. Thank you for your work. Can you recommend me some long range bluetooth (minimum 5.0) adapter working with kali and working min for 500m or can cover 8 floor building? Cheapest 🙂

**Comment by 0xbitx** [comment]
Parani-UD100

**Comment by hisbalah** [comment]
Thank you . And one more question. What is a range of this Jammer? How many meters?

**Comment by Asmodeux2** [comment]
Радиус действия особо не большой , от силы 1 метр (100 см) со всем штатным оборудованием😏 Nrf лучше заменить на модули Lora и взять иные антенны для модулей и радиус увеличится в 3 раза
