### ISSUE TITLE
Did the "BlueJammer" project really just copy your code?

### ISSUE THREAD

**Issue by Verqlickt** [0xbitx/DEDSEC_BLUEJACKER#5]
First of all, really good work!

but I just saw your issue on the BlueJammer Project, is this true that BlueJammer is just a copycat of the Bluejacker? 
And btw could you send me the hex file from the Bluejammer project? Because after your issue it went closed source...

Oh yea and btw your discord link in your Blog is broken.

**Comment by 0xbitx** [comment]
https://github.com/EmenstaNougat/ESP32-BlueJammer/commit/876a

**Comment by smoochiee** [comment]
> [EmenstaNougat/ESP32-BlueJammer@876a](https://github.com/EmenstaNougat/ESP32-BlueJammer/commit/876a)

https://github.com/smoochiee/Bluetooth-jammer-esp32
